import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { getSupabaseServerClient } from "@/lib/supabase/server";
import { signOut } from "@/app/actions";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await getSupabaseServerClient();
  const session = supabase ? (await supabase.auth.getSession()).data.session : null;
  const username = session && supabase
    ? (await supabase
        .from("profiles")
        .select("username")
        .eq("id", session.user.id)
        .single()
      ).data?.username
    : null;
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50`}>
        <header className="border-b bg-white">
          <div className="mx-auto max-w-2xl px-4 py-3 flex items-center justify-between">
            <Link href="/" className="font-semibold">
              SNS App
            </Link>
            <div className="flex items-center gap-3">
              {session && (
                <Link href="/timeline" className="text-sm underline">
                  Timeline
                </Link>
              )}
              {username && (
                <Link href={`/u/${username}`} className="text-sm underline">
                  My Profile
                </Link>
              )}
              {session ? (
                <form action={signOut}>
                  <button className="rounded-md bg-gray-100 hover:bg-gray-200 px-3 py-1 text-sm">
                    Sign out
                  </button>
                </form>
              ) : (
                <Link href="/login" className="text-sm underline">Sign in</Link>
              )}
            </div>
          </div>
        </header>
        <main className="mx-auto max-w-2xl px-4 py-6">{children}</main>
      </body>
    </html>
  );
}
